package utoo.offlinecacheanddeeplink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUESTION_DATA".
 */
public class QuestionData {

    private long id;
    private String asked_by;
    private String description;
    private String status;
    private Long user_id;
    private Long answer_tutor_id;
    private String answered_by;
    private String created_at;
    private String subject;
    private String picture_url;
    private Double user_rating;

    public QuestionData() {
    }

    public QuestionData(long id, String asked_by, String description, String status, Long user_id, Long answer_tutor_id, String answered_by, String created_at, String subject, String picture_url, Double user_rating) {
        this.id = id;
        this.asked_by = asked_by;
        this.description = description;
        this.status = status;
        this.user_id = user_id;
        this.answer_tutor_id = answer_tutor_id;
        this.answered_by = answered_by;
        this.created_at = created_at;
        this.subject = subject;
        this.picture_url = picture_url;
        this.user_rating = user_rating;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAsked_by() {
        return asked_by;
    }

    public void setAsked_by(String asked_by) {
        this.asked_by = asked_by;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Long getAnswer_tutor_id() {
        return answer_tutor_id;
    }

    public void setAnswer_tutor_id(Long answer_tutor_id) {
        this.answer_tutor_id = answer_tutor_id;
    }

    public String getAnswered_by() {
        return answered_by;
    }

    public void setAnswered_by(String answered_by) {
        this.answered_by = answered_by;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getPicture_url() {
        return picture_url;
    }

    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url;
    }

    public Double getUser_rating() {
        return user_rating;
    }

    public void setUser_rating(Double user_rating) {
        this.user_rating = user_rating;
    }

}
