package utoo.offlinecacheanddeeplink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REGION_DATA".
 */
public class RegionData {

    private long id;
    private String name;
    private String full_name;

    public RegionData() {
    }

    public RegionData(long id, String name, String full_name) {
        this.id = id;
        this.name = name;
        this.full_name = full_name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFull_name() {
        return full_name;
    }

    public void setFull_name(String full_name) {
        this.full_name = full_name;
    }

}
