package utoo.offlinecacheanddeeplink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUBJECT_DATA".
 */
public class SubjectData {

    private long id;
    private String abbr;
    private String description;
    private String region;

    public SubjectData() {
    }

    public SubjectData(long id, String abbr, String description, String region) {
        this.id = id;
        this.abbr = abbr;
        this.description = description;
        this.region = region;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAbbr() {
        return abbr;
    }

    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

}
