package utoo.offlinecacheanddeeplink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private long id;
    private String gender;
    private String name;
    private String email;
    private String username;
    private Long registered;
    private Long dob;
    private String school;
    private String country_code;
    private String phone;
    private String profile_pic_url;
    private String role;
    private Double rating;
    private Double rating_total;

    public User() {
    }

    public User(long id, String gender, String name, String email, String username, Long registered, Long dob, String school, String country_code, String phone, String profile_pic_url, String role, Double rating, Double rating_total) {
        this.id = id;
        this.gender = gender;
        this.name = name;
        this.email = email;
        this.username = username;
        this.registered = registered;
        this.dob = dob;
        this.school = school;
        this.country_code = country_code;
        this.phone = phone;
        this.profile_pic_url = profile_pic_url;
        this.role = role;
        this.rating = rating;
        this.rating_total = rating_total;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Long getRegistered() {
        return registered;
    }

    public void setRegistered(Long registered) {
        this.registered = registered;
    }

    public Long getDob() {
        return dob;
    }

    public void setDob(Long dob) {
        this.dob = dob;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getCountry_code() {
        return country_code;
    }

    public void setCountry_code(String country_code) {
        this.country_code = country_code;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getProfile_pic_url() {
        return profile_pic_url;
    }

    public void setProfile_pic_url(String profile_pic_url) {
        this.profile_pic_url = profile_pic_url;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Double getRating_total() {
        return rating_total;
    }

    public void setRating_total(Double rating_total) {
        this.rating_total = rating_total;
    }

}
